<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns2:ProcessESCRequest xmlns:ns2="http://standardbank.co.za/sa/services/Technical/Integration/Integration/PS_ESC_LegacyStatementDataV1" xmlns="http://standardbank.co.za/sa/services/Global/IfxV2_1/HeaderV2_0">
         <RqUID>633970bd-0700-4691-8c7e-876b53997fc2</RqUID>
         <MsgRqHdr>
            <SvcIdent>
               <SvcProviderName>ESB</SvcProviderName>
            </SvcIdent>
            <ContextRqHdr>
               <ClientTerminalSeqNum>RBDSB003</ClientTerminalSeqNum>
               <NetworkTrnData>
                  <NetworkOwner>Branch</NetworkOwner>
                  <Name>18252</Name>
                  <AcquirerIdent>A213314</AcquirerIdent>
                  <ContentTypeXSB>TEXT/XML</ContentTypeXSB>
                  <ClientProcessingModeXSB>A</ClientProcessingModeXSB>
                  <InterfaceNameXSB>MCAF</InterfaceNameXSB>
               </NetworkTrnData>
               <ClientDt>2020-11-17T14:48:07+00:03</ClientDt>
               <ClientApp>
                  <Org>PBBSA</Org>
                  <Name>043</Name>
                  <Version>0001</Version>
                  <SrcSystemXSB>003</SrcSystemXSB>
               </ClientApp>
               <MsgGroupReference>633970bd-0700-4691-8c7e-876b53997fc2</MsgGroupReference>
            </ContextRqHdr>
         </MsgRqHdr>
         <ns2:StatementData>
            <ns2:business_contents>
               <ns2:output_accounts>
                  <ns2:account>
                     <ns2:number>0000080399630000</ns2:number>
                     <ns2:last_deposit_date xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                  </ns2:account>
               </ns2:output_accounts>
            </ns2:business_contents>
            <ns2:operational>
               <ns2:request_number>182523221448419113</ns2:request_number>
               <ns2:function_number>9999</ns2:function_number>
               <ns2:userid>A213314</ns2:userid>
               <ns2:channel_id>BDSJ</ns2:channel_id>
               <ns2:centre_number>18252</ns2:centre_number>
               <ns2:device_id>RBDSB003</ns2:device_id>
               <ns2:compression_CHNL_ESC>Y</ns2:compression_CHNL_ESC>
            </ns2:operational>
            <ns2:routing_contents>
               <ns2:service>
                  <ns2:name>ACNTENQ</ns2:name>
                  <ns2:version>1</ns2:version>
               </ns2:service>
            </ns2:routing_contents>
         </ns2:StatementData>
      </ns2:ProcessESCRequest>
   </soapenv:Body>
</soapenv:Envelope>